/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package vending.machine

data class Product(val name: String, val price: Int, var stock: Int = 10) {
    fun addStock(stock: Int) {
        this.stock += stock
    }
}


class VendingMachine(val products: MutableList<Product>) {
    enum class Status {
        ForSale, UnderMaintenance
    }

    private var status: Status = Status.UnderMaintenance

    fun getStatus(): Status {
        return this.status
    }

    fun changeStatusMaintenance() {
        this.status = Status.UnderMaintenance
    }

    fun changeStatusSale() {
        this.status = Status.ForSale
    }

    val isForSale: Boolean
        get() {
            return this.status == Status.ForSale
        }

    val isUnderMaintenance: Boolean
        get() {
            return this.status == Status.UnderMaintenance
        }


}

fun main() {
    var initProducts: MutableList<Product> = mutableListOf(
        Product("초코 우유", 1500, 20),
        Product("딸기 우유", 1500, 10),
        Product("옥수수킥", 1000, 8),
        Product("별다방 커피", 2500, 15),
        Product("뒤로가기 커피", 2000, 20),
        Product("포켓몬빵", 3000, 0),
    )
    val vm = VendingMachine(initProducts)
    vm.changeStatusSale()
    println(vm.getStatus())
    println(vm.isForSale)
    println(vm.isUnderMaintenance)

}
